# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "First lane"
  
  lane :example do
    # add actions here: https://docs.fastlane.tools/actions
    puts("this is my first 🚀 lane")
  end

lane :beta do
gym(
    scheme: "UniversalTextStyle",
    export_method: "development",
  )
hockey(
  api_token: "6a4856385a8142cc976cfb157cdd5311",
  ipa: "./UniversalTextStyle.ipa",
  notes: "Build from fastlane!"
) 

end

end
